// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChessGame struct {
	ID            string       `json:"id"`
	ReceiverID    string       `json:"receiverId"`
	ReceiverColor string       `json:"receiverColor"`
	RequesterID   string       `json:"requesterId"`
	Users         []*ChessUser `json:"users"`
	Moves         []*ChessMove `json:"moves"`
	Fen           string       `json:"fen"`
	Turn          string       `json:"turn"`
	Started       bool         `json:"started"`
}

type ChessMove struct {
	From      string  `json:"from"`
	To        string  `json:"to"`
	Promotion *string `json:"promotion,omitempty"`
	EndFen    string  `json:"endFen"`
}

type ChessRequest struct {
	GameID         string `json:"gameId"`
	RequesterID    string `json:"requesterId"`
	RequesterColor string `json:"requesterColor"`
	ReceiverID     string `json:"receiverId"`
}

type ChessUser struct {
	ID            string          `json:"id"`
	Username      string          `json:"username"`
	LastSeen      string          `json:"last_seen"`
	CatURL        string          `json:"cat_url"`
	ChessRequests []*ChessRequest `json:"chessRequests,omitempty"`
}
